# Generated by Django 6.1 on 2026-08-12 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(help_text='AAAA-MM', max_length=7)),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='processando', max_length=15)),
                ('usar_api_totvs', models.BooleanField(default=False, help_text='Se marcado, colaboradores vêm da API do TOTVS RM em vez de upload')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('erro_mensagem', models.TextField(blank=True)),
                ('arquivo_txt', models.FileField(blank=True, null=True, upload_to='execucoes/%Y/%m/')),
                ('arquivo_relatorio', models.FileField(blank=True, null=True, upload_to='execucoes/%Y/%m/')),
                ('iniciado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Execução de Cálculo',
                'verbose_name_plural': 'Execuções de Cálculo',
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('colaboradores', 'Colaboradores (TOTVS RM)'), ('coral', 'Coral — faturamento/DMA (dma-accumulated)'), ('nps', 'NPS por loja (Power BI)'), ('preventiva', 'Preventivas (Frotas)'), ('bate_patio', 'Fechamento / Bate Pátio (Frotas)'), ('nonrev', 'NONREV (Frotas)'), ('meta_faturamento', 'Meta de Faturamento (Importação Planilha)'), ('mapeamento', 'Lista de Logins (login → matrícula)')], max_length=30)),
                ('arquivo', models.FileField(upload_to='uploads/%Y/%m/')),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='calculo.execucaocalculo')),
            ],
            options={
                'verbose_name': 'Arquivo Enviado',
                'verbose_name_plural': 'Arquivos Enviados',
            },
        ),
    ]
