# Generated by Django 6.1 on 2026-08-12 11:47

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.SlugField(help_text='Minúsculo, sem espaços — ex: lider_frota', unique=True)),
                ('modelo', models.CharField(choices=[('percentual', '% do Salário'), ('teto_fixo', 'Teto Fixo (R$)')], max_length=20)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ParametroTOTVS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=50, unique=True)),
                ('valor', models.CharField(max_length=200)),
                ('descricao', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Parâmetro TOTVS',
                'verbose_name_plural': 'Parâmetros TOTVS',
                'ordering': ['parametro'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome exato conforme retornado pelo TOTVS RM', max_length=150, unique=True)),
                ('teto', models.DecimalField(blank=True, decimal_places=2, help_text="Obrigatório se o grupo for de modelo 'Teto Fixo'", max_digits=10, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='regras.grupo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCargo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, help_text='Nome exato conforme retornado pelo TOTVS RM', max_length=150)),
                ('teto', models.DecimalField(blank=True, decimal_places=2, help_text="Obrigatório se o grupo for de modelo 'Teto Fixo'", max_digits=10, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('grupo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='regras.grupo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cargo',
                'verbose_name_plural': 'historical Cargos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGrupo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.SlugField(help_text='Minúsculo, sem espaços — ex: lider_frota')),
                ('modelo', models.CharField(choices=[('percentual', '% do Salário'), ('teto_fixo', 'Teto Fixo (R$)')], max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Grupo',
                'verbose_name_plural': 'historical Grupos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIndicadorRegra',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('indicador', models.CharField(choices=[('dma', 'DMA'), ('nps', 'NPS'), ('faturamento', 'Faturamento (% atingimento)'), ('nonrev', 'NONREV'), ('preventiva', 'Preventiva'), ('bate_patio', 'Bate Pátio')], max_length=20)),
                ('direcao', models.CharField(choices=[('maior', 'Maior é melhor'), ('menor', 'Menor é melhor')], default='maior', max_length=10)),
                ('chave_meta', models.CharField(blank=True, help_text='Se preenchido, os limites (min/max) vêm de Metas Mensais em vez das faixas abaixo', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('grupo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='regras.grupo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Indicador de Regra',
                'verbose_name_plural': 'historical Indicadores de Regra',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMetaMensal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('mes', models.CharField(help_text='AAAA-MM, ex: 2026-06', max_length=7)),
                ('chave', models.CharField(help_text='Ex: nps_lider_frota, nonrev', max_length=50)),
                ('faixa', models.PositiveSmallIntegerField()),
                ('valor_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('valor_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Meta Mensal',
                'verbose_name_plural': 'historical Metas Mensais',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalParametroTOTVS',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('parametro', models.CharField(db_index=True, max_length=50)),
                ('valor', models.CharField(max_length=200)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Parâmetro TOTVS',
                'verbose_name_plural': 'historical Parâmetros TOTVS',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='IndicadorRegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.CharField(choices=[('dma', 'DMA'), ('nps', 'NPS'), ('faturamento', 'Faturamento (% atingimento)'), ('nonrev', 'NONREV'), ('preventiva', 'Preventiva'), ('bate_patio', 'Bate Pátio')], max_length=20)),
                ('direcao', models.CharField(choices=[('maior', 'Maior é melhor'), ('menor', 'Menor é melhor')], default='maior', max_length=10)),
                ('chave_meta', models.CharField(blank=True, help_text='Se preenchido, os limites (min/max) vêm de Metas Mensais em vez das faixas abaixo', max_length=50)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='regras.grupo')),
            ],
            options={
                'verbose_name': 'Indicador de Regra',
                'verbose_name_plural': 'Indicadores de Regra',
                'ordering': ['grupo__nome', 'indicador'],
                'unique_together': {('grupo', 'indicador')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalFaixaCalculo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('faixa', models.PositiveSmallIntegerField(help_text='1, 2, 3... — maior número = melhor faixa')),
                ('valor_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('valor_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('pct', models.DecimalField(decimal_places=4, help_text='Ex: 0,15 = 15% do salário/teto', max_digits=6)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('indicador_regra', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='regras.indicadorregra')),
            ],
            options={
                'verbose_name': 'historical Faixa de Cálculo',
                'verbose_name_plural': 'historical Faixas de Cálculo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MetaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(help_text='AAAA-MM, ex: 2026-06', max_length=7)),
                ('chave', models.CharField(help_text='Ex: nps_lider_frota, nonrev', max_length=50)),
                ('faixa', models.PositiveSmallIntegerField()),
                ('valor_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('valor_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Meta Mensal',
                'verbose_name_plural': 'Metas Mensais',
                'ordering': ['-mes', 'chave', 'faixa'],
                'unique_together': {('mes', 'chave', 'faixa')},
            },
        ),
        migrations.CreateModel(
            name='FaixaCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa', models.PositiveSmallIntegerField(help_text='1, 2, 3... — maior número = melhor faixa')),
                ('valor_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('valor_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('pct', models.DecimalField(decimal_places=4, help_text='Ex: 0,15 = 15% do salário/teto', max_digits=6)),
                ('indicador_regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='regras.indicadorregra')),
            ],
            options={
                'verbose_name': 'Faixa de Cálculo',
                'verbose_name_plural': 'Faixas de Cálculo',
                'ordering': ['indicador_regra', 'faixa'],
                'unique_together': {('indicador_regra', 'faixa')},
            },
        ),
    ]
