# Generated by Django 6.1 on 2026-08-25 13:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(help_text='Código da loja no TOTVS, ex: SAO10', max_length=20, unique=True)),
                ('regional', models.CharField(help_text='Ex: NORDESTE, SUDESTE, SUL', max_length=50)),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'ordering': ['regional', 'unidade'],
            },
        ),
        migrations.AlterField(
            model_name='grupo',
            name='modelo',
            field=models.CharField(choices=[('percentual', '% do Salário'), ('teto_fixo', 'Teto Fixo (R$)'), ('desconsiderar', 'Desconsiderar (sem RV)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalgrupo',
            name='modelo',
            field=models.CharField(choices=[('percentual', '% do Salário'), ('teto_fixo', 'Teto Fixo (R$)'), ('desconsiderar', 'Desconsiderar (sem RV)')], max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricalLoja',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('unidade', models.CharField(db_index=True, help_text='Código da loja no TOTVS, ex: SAO10', max_length=20)),
                ('regional', models.CharField(help_text='Ex: NORDESTE, SUDESTE, SUL', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Loja',
                'verbose_name_plural': 'historical Lojas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMetaFaturamentoRegional',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('mes', models.CharField(help_text='AAAA-MM, ex: 2026-06', max_length=7)),
                ('regional', models.CharField(help_text='Ex: NORDESTE, SUDESTE, SUL', max_length=50)),
                ('meta', models.DecimalField(decimal_places=2, help_text='Meta de faturamento em R$', max_digits=12)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Meta de Faturamento Regional',
                'verbose_name_plural': 'historical Metas de Faturamento Regional',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MetaFaturamentoRegional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(help_text='AAAA-MM, ex: 2026-06', max_length=7)),
                ('regional', models.CharField(help_text='Ex: NORDESTE, SUDESTE, SUL', max_length=50)),
                ('meta', models.DecimalField(decimal_places=2, help_text='Meta de faturamento em R$', max_digits=12)),
            ],
            options={
                'verbose_name': 'Meta de Faturamento Regional',
                'verbose_name_plural': 'Metas de Faturamento Regional',
                'ordering': ['-mes', 'regional'],
                'unique_together': {('mes', 'regional')},
            },
        ),
    ]
