# Generated by Django 6.1 on 2026-09-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regras', '0002_loja_alter_grupo_modelo_alter_historicalgrupo_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalindicadorregra',
            name='depende_indicador',
            field=models.CharField(blank=True, choices=[('dma', 'DMA'), ('nps', 'NPS'), ('faturamento', 'Faturamento (% atingimento)'), ('nonrev', 'NONREV'), ('preventiva', 'Preventiva'), ('bate_patio', 'Bate Pátio')], help_text="Opcional: outro indicador do MESMO grupo do qual este depende — ex: 'dma' só conta se 'faturamento' bater o valor mínimo abaixo. Em branco = sem dependência (padrão).", max_length=20),
        ),
        migrations.AddField(
            model_name='historicalindicadorregra',
            name='depende_valor_min',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Valor real mínimo (não faixa) que 'Depende indicador' precisa atingir", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='indicadorregra',
            name='depende_indicador',
            field=models.CharField(blank=True, choices=[('dma', 'DMA'), ('nps', 'NPS'), ('faturamento', 'Faturamento (% atingimento)'), ('nonrev', 'NONREV'), ('preventiva', 'Preventiva'), ('bate_patio', 'Bate Pátio')], help_text="Opcional: outro indicador do MESMO grupo do qual este depende — ex: 'dma' só conta se 'faturamento' bater o valor mínimo abaixo. Em branco = sem dependência (padrão).", max_length=20),
        ),
        migrations.AddField(
            model_name='indicadorregra',
            name='depende_valor_min',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Valor real mínimo (não faixa) que 'Depende indicador' precisa atingir", max_digits=10, null=True),
        ),
    ]
