# Generated by Django 6.1 on 2026-09-02 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regras', '0003_historicalindicadorregra_depende_indicador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoReferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('identificador_lote', models.CharField(max_length=40, unique=True)),
                ('resumo', models.TextField(blank=True, help_text='Ex: 9 grupos, 48 cargos, 24 indicadores...')),
                ('status', models.CharField(choices=[('aplicada', 'Aplicada'), ('revertida', 'Revertida')], default='aplicada', max_length=10)),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.ForeignKey(blank=True, help_text='Quem reverteu ou reaplicou por último', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('importado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importacoes_feitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importação de Referências',
                'verbose_name_plural': 'Importações de Referências',
                'ordering': ['-importado_em'],
            },
        ),
    ]
