# Generated by Django 6.1 on 2026-09-02 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regras', '0004_importacaoreferencias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicadorregra',
            options={'ordering': ['grupo__nome', 'indicador', 'loja__unidade'], 'verbose_name': 'Indicador de Regra', 'verbose_name_plural': 'Indicadores de Regra'},
        ),
        migrations.AlterUniqueTogether(
            name='indicadorregra',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historicalindicadorregra',
            name='loja',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Opcional: deixe em branco pra regra padrão (nacional), válida pra quem não tiver uma regra específica. Preencha só se essa loja precisar de faixas diferentes das do padrão pra esse indicador.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='regras.loja'),
        ),
        migrations.AddField(
            model_name='indicadorregra',
            name='loja',
            field=models.ForeignKey(blank=True, help_text='Opcional: deixe em branco pra regra padrão (nacional), válida pra quem não tiver uma regra específica. Preencha só se essa loja precisar de faixas diferentes das do padrão pra esse indicador.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras_especificas', to='regras.loja'),
        ),
        migrations.AlterUniqueTogether(
            name='indicadorregra',
            unique_together={('grupo', 'indicador', 'loja')},
        ),
    ]
